USE NBNData
GO

DROP TABLE [MAPINFO].[MAPINFO_MAPCATALOG]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [MAPINFO].[MAPINFO_MAPCATALOG](
	[SPATIALTYPE] [float] NULL,
	[TABLENAME] [varchar](32) NULL,
	[OWNERNAME] [varchar](32) NULL,
	[SPATIALCOLUMN] [varchar](32) NULL,
	[DB_X_LL] [float] NULL,
	[DB_Y_LL] [float] NULL,
	[DB_X_UR] [float] NULL,
	[DB_Y_UR] [float] NULL,
	[COORDINATESYSTEM] [varchar](254) NULL,
	[SYMBOL] [varchar](254) NULL,
	[XCOLUMNNAME] [varchar](32) NULL,
	[YCOLUMNNAME] [varchar](32) NULL,
	[RENDITIONTYPE] [int] NULL,
	[RENDITIONCOLUMN] [varchar](32) NULL,
	[RENDITIONTABLE] [varchar](32) NULL,
	[NUMBER_ROWS] [int] NULL,
	[VIEW_X_LL] [float] NULL,
	[VIEW_Y_LL] [float] NULL,
	[VIEW_X_UR] [float] NULL,
	[VIEW_Y_UR] [float] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
