USE NBNData
GO

/****** Object:  Table [dbo].[TVERC_Taxon_Designation_Types]    Script Date: 30/03/2016 15:01:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TVERC_Taxon_Designation_Types](
	[TAXON_DESIGNATION_TYPE_KEY] [char](16) NOT NULL,
	[Status_Abbreviation] [varchar](25) NULL,
	[Sort_Order] [int] NULL,
 CONSTRAINT [PK_TVERC_TAXON_DESIGNATION_TYPE] PRIMARY KEY CLUSTERED 
(
	[TAXON_DESIGNATION_TYPE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
